/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("com.github.ajalt.clikt:clikt:5.0.3")
    implementation("org.apache.commons:commons-text")
    implementation(project(":core"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
